config/routes.rb
Moviedb::Application.routes.draw do
  get "welcome/index"
  resources :actors
  resources :welcome

  root 'actors#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :actor_movie
  has_many :movies, through: :actor_movie

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/actor_movie.rb
class ActorMovie < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie
end

app/models/actors_movies.rb
class ActorsMovies < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :actor_movie
  has_many :actors, through: :actor_movie
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  require 'will_paginate/array'

  def index
    @movies = Movie.all
    @actor = Actor.new

    # Actor search form
    if params[:search]
    # @actor = Actor.where("name LIKE ?", "%#{params[:search].capitalize}%")
      @actors = Actor.where(name: /^#{Regexp.escape(params[:search])}/i)
    else
      @actors = Actor.all.paginate(page: params[:page], per_page: 8)
    end

    # respond_to do |format|
    #   format.html {}
    #   format.js
    #   format.json { render json: @actors}
    # end
  end



  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies.where("total_revenue > ?", 10000000).where("budget > ?", 100) .order("total_revenue DESC")
    @fresh = @actor.movies.where("freshness >= ?", 70).order("freshness DESC")
    @rotten = @actor.movies.where("freshness <= ?", 60).order("freshness ASC")
    # @newest = @actor.movies.where("release_year >= ?", 2010).order("freshness DESC")
    # @oldest = @actor.movies.where("release_year <= ?", 2010).order("freshness ASC")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/_actorlist.html.erb
<div class="container">
  <div class="row">
    <% i = 1 %>
    <% @actors.each do |actor| %>
      <figure class="col-md-3 col-sm-6 col-xs-12">
      <a href="<%=actor_path(actor)%>"><img class="pictureframe" src="http://image.tmdb.org/t/p/original<%= actor.picture %>" alt="<%= actor.name %>" /><% actor_path(actor) %></a>
      <figcaption><%= actor.name %></figcaption>
      </figure>
      <% if i % 4 == 0 %>
        </div>
        <div class="row">
      <% end %>
      <% i += 1 %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
  $("#filter").keyup(function(){

    // Retrieve the input field text and reset the count to zero
    var filter = $(this).val(), count = 0;

    // Loop through the comment list
    // $(".commentlist li").each(function(){
    $("figure").each(function(){

      // If the list item does not contain the text phrase fade it out
      if ($(this).text().search(new RegExp(filter, "i")) < 0) {
        $(this).fadeOut();

        // Show the list item if the phrase matches and increase the count by 1
      } else {
            $(this).show();
      }
    });
  });
});





</script>

app/views/actors/_actors_search_section.erb
<div class="row" id="actors-search-section">
	<!-- Start actor display -->
  	<% @actors.each do |actor| %>
    <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12 card">
    	<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
    		<div class="flipper">
    			<div class="front">
	    			<!-- front content -->
	    			<div class="actor-profile">
				        <a href="<%=actor_path(actor)%>"><img class="pictureframe" src="http://image.tmdb.org/t/p/original<%= actor.picture %>" alt="<%= actor.name %>" /><% actor_path(actor) %></a>
				    </div>

			 			<div class="actor-profile-content">
			 				<h4><%= actor.name %></h4>
	
			 			</div>
			 		</div>
			 		<div class = "back">
			 			<div class="actor-profile-header">
			 				<h4><%= link_to actor.name, actor_path(actor) %></h4>
			 			</div>
			 				<p>Age: <%= Time.now.year - Date.strptime(actor.birthdate).year %></p>
			 				<!-- back content -->

			 				<p><%= truncate(actor.bio, length: 200, omission: '...(more)') %></p>	

			 	</div>
			</div>
		</div>
	</div>
	<!-- End of actors display -->	
	 <% end %>
</div>

app/views/actors/_nav.html.erb
<nav>
  <%= link_to 'ActDat', root_path, class: "logo"%>

	<div id="searchbar">
	    <%= form_tag actors_path, method: 'post', id: "live-search", class: "styled" do %>
	    <%= text_field_tag :search, params[:search], placeholder: "Search by Actor Name!", class: "text-input",
	     id: "filter" %>
	    <span id="filter-count"></span>
	    <% end %>
	</div>

	<div class="nav navbar-nav navbar-right" id="ad_logo"><%= link_to image_tag('adlogo.png') %></div>

</nav>

app/views/actors/_nav_show.html.erb
<nav>
  <%= link_to 'ActDat', root_path, class: "logo"%>
</nav>

app/views/actors/index.html.erb
<style type="text/css">
	nav {
		padding-bottom: 10px;
	}
	#logo {
		color: white;
	}
	#ad-logo img {
		height: 50px;
		width: 50px;
	}

	#searchbar {
		margin-top: 5%;
	}

	input#search{
		color: white;
		background-color: transparent;
	}

	#ad-logo {
		margin-top: 5%;
	}
		
	input#search {text-align: center}

	#actor_dis {
		padding-top: 20px;
	}


</style>

<nav>
	<div class="container-fluid">
		<div class="row">
			<!-- logo -->
			<div class="col-md-3 col-sm-3 col-xs-12 text-center">
				<h1 id="logo"> ActDat</h1>
			</div>

			<div class="col-md-6 col-sm-6 col-xs-12 text-center">
			    <!-- search box here -->
			    <div id="searchbar">
				    <%= form_tag actors_path, method: 'get', id: 'search_box' do %>
				      <%= text_field_tag :search, params[:search], placeholder: "Search Actors" %>
				    <% end %>
			    </div>
			</div>

			<!-- second logo -->

			<div class="col-md-3 col-sm-3 col-xs-12 text-center">
				<div id="ad-logo"><%= link_to image_tag('adlogo.png') %></div>
			</div>

		</div>
	</div>


</nav>

<div id="actor_dis">
<div class="container">
	<div class="col-md-12 col-lg-12 col-sm-12" id="profiles-panel">
    <!-- Actors search section -->
    <%= render partial: 'actors_search_section' %>

  </div>
</div>


<%= will_paginate @actors %>
</div>














<!------

<div><%#= render 'nav' %></div>

<div id="actors">
  
  <%#= render 'actor' %>

</div>

<div class="pagination"> 
  <#%= will_paginate @actors_pagination %>
</div>
<script type="text/javascript">
$('img').insetBorder({
  inset : 10,
  borderColor : '#ffffff',
  speed : 250,
  borderType : 'solid'
});
</script>


-->

app/views/actors/index.js.erb
// Actor search
<% if params[:search] %>
  $("#actors-search-section").html('<%= j render partial: "actors_search_section" %>');
<% end %>

// Endless scroll pagination
<% if params[:page] %>
	$('#actors-search-section').append('<%= j render partial: "actors_search_section" %>');
	<% if @actors.next_page %>
	  $('.pagination').replaceWith('<%= j will_paginate(@actors) %>');
	<% else %>
	  // $(window).off('scroll');
	  $('.pagination').remove();
	<% end %>
	<% sleep 1 %>
<% end %>

app/views/actors/show.html.erb
<!------ D3 and Tips Scripts ---------->
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script> <!-- bringing in d3 -->
    <script src="http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"></script>
<%= render 'nav_show' %>

<h3 class="actornameshow"><%= @actor.name.upcase %></h3>
<div class="show_top_container">
<div class="imagewrapper"><img src="http://image.tmdb.org/t/p/original<%= @actor.picture %>"/></div>


<section class="quote">
  "<%= @actor.quote %>"
</section>
</div>
<!-- <div id="triangle_down1"></div> -->

<div class="stripe">
  <section class="bio">
    <div id="talkbubble1">ACTOR FUN FACTS!!!</div>
    <%= truncate(@actor.bio, length: 500, omission: '...(more)') %>
  </section>
</div>

<!-- Rotten Tomatoes top and bottom critics score lists -->
<div class="stripe">  
  <aside>
    <ol>
      <h3 class="list_header">Top Fresh Movies</h3>
      <li><p><%= @fresh[0].title %> - <%#= @fresh[0].freshness %>%</p></li>
      <li><p><%= @fresh[1].title %> - <%#= @fresh[1].freshness %>%</p></li>
      <li><p><%= @fresh[2].title %> - <%#= @fresh[2].freshness %>%</p></li>
    </ol>
    <ol>
      <h3 class="list_header">Bottom Rotten Movies</h3>
      <li><p><%= @rotten[0].title %> - <%#= @rotten[0].freshness %>%</p></li>
      <li><p><%= @rotten[1].title %> - <%#= @rotten[1].freshness %>%</p></li>
      <li><p><%= @rotten[2].title %> - <%#= @rotten[2].freshness %>%</p></li>
    </ol>
  </aside>
</div>
  <div id="triangle_down1"></div><!--  triangle at bottom of div -->
  <!-- arrow point to Rotten Tomatoe Lists -->
  <div id="talkbubble2">ROTTEN TOMATES INFO!!!</div>

<!-- header for boxx office D3 bar chart -->
<div class="chart_header"><h3>BOX OFFICES GROSSES</h3>
<!-- d3 box office bar chart -->
  <div class="chart"></div>
    <div class="btn_contain">
      <div class="bar_btns">
        <button type="button" class="btn btn-default" id="total">Total</button>
        <button type="button" class="btn btn-default" id="domestic">Domestic</button>
        <button type="button" class="btn btn-default" id="international">International</button>
      </div>
      <div id="triangle_down2"></div> <!--  triange at bottom of div -->
    </div>
</div>
<!-- D3 pie chart for budgets -->

<div class="pie_chart">
  <h2 class="budget_header">Movie Budgets</h2>
</div>
<!-- <div class="budget_btns">
  <div class="radio">
    <input type="radio" name="dataset" value="topData" checked><label>Highest Budget</label>
  </div>
  <div class="radio">
    <input type="radio" name="dataset" value="botData"><label>Lowest Budget</label>
  </div>
</div> -->

<script>
window.d3_url = '<%= actor_path(@actor, format: 'json') %>';
toggle_total();
pieChart();
</script>

app/views/actors/show.js.erb
$(document).ready( function(){$("#total").click(function(){
// $(window).load( function(){$("#total").click(function(){
  // event.preventDefault()
    
    $(".chart").html("");
    toggle_total();
    // $(".bar").slideDown();
    $(".chart").slideDown();
    console.log("hi")
  });

  $("#international").click(function(){
    $(".chart").html("");
    $(".chart").change(toggle_intl());
  });

  $("#domestic").click(function(){
    $(".chart").html("");
    $(".chart").change(toggle_dom());
  });
});

  var formatNumber = d3.format(",");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Actor DataBase - a place where movie data are pleasing to the eyes</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <link href='http://fonts.googleapis.com/css?family=Reenie+Beanie' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Poiret+One|Fascinate+Inline|Muli|Sofadi+One' rel='stylesheet' type='text/css'>




	  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
<body>

	<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>